# Assignment 1

In [2]:
import numpy as np

### Q1

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])
reverse_arr = arr[::-1]
print(reverse_arr)

[5 4 6 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [5]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
array2 = array1.flatten()
print(array2)
array3 = array1.ravel()
print(array3)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:
<br>arr1 = np.array([[1, 2], [3, 4]])
<br>arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print(arr1 == arr2)                 # Element wise equality check
print()
print(np.array_equal(arr1, arr2))   # Overall array equality check

[[ True  True]
 [ True  True]]

True


(d) Find the most frequent value and their indice(s) in the following arrays:
<br>i. x = np.array([1,2,3,4,5,1,2,1,1,1])
<br>ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [17]:
# (i.)
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
value = np.bincount(x).argmax()
print("Most frequent value in the array:", value)
print("\nIndices of the most frequent value in the array:")
for i in range(len(x)):
    if x[i] == value:
        print(i, end = " ")

print("\n")
# (ii.)
# Since more than one element has the maximum frequency
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
print("Most frequent value in above array: ")
count = np.bincount(y)
maximum = max(count)

for i in range(len(count)):
    if count[i] == maximum:
        print(i, end = " ")

Most frequent value in the array: 1

Indices of the most frequent value in the array:
0 5 7 8 9 

Most frequent value in above array: 
1 3 

(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
<br>i. Sum of all elements
<br>ii. Sum of all elements row-wise
<br>iii. Sum of all elements column-wise

In [16]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

# (i.)
print("sum of all elements: ", np.sum(gfg))

# (ii.)
print("\nRow wise sum of elements: ", gfg.sum(axis=0))

# (iii.)
print("\nColumn wise sum of elements:\n", gfg.sum(axis=1))

sum of all elements:  45

Row wise sum of elements:  [[20  9 16]]

Column wise sum of elements:
 [[14]
 [16]
 [15]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
<br>i. Sum of diagonal elements
<br>ii. Eigen values of matrix
<br>iii. Eigen vectors of matrix
<br>iv. Inverse of matrix
<br>v. Determinant of matrix

In [ ]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

# (i.) Sum of diagonal elements
trace = np.trace(n_array)
print("Sum of diagonal elements: ", trace, "\n")

# (ii.) & (iii.) Eigenvalues and Eigenvectors
eigvals, eigvecs = np.linalg.eig(n_array)
print("Eigenvalues: ", eigvals, "\n")
print("Eigenvectors: ", eigvecs, "\n")

# (iv.) Inverse
inverse = np.linalg.inv(n_array)
print("Inverse of the matrix: ", inverse, "\n")

# (v.) Determinant
determinant = np.linalg.det(n_array)
print("Determinant of the matrix: ", determinant, "\n")

Sum of diagonal elements:  176 

Eigenvalues:  [98.16835147 28.097044   49.73460452] 

Eigenvectors:  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]] 

Inverse of the matrix:  [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]] 

Determinant of the matrix:  137180.0000000001 



(g) Multiply the following matrices and also find covariance between matrices using NumPy:
<br>i. p = [[1, 2], [2, 3]]
<br><t>q = [[4, 5], [6, 7]]
<br>ii. p = [[1, 2], [2, 3], [4, 5]]
<br>        q = [[4, 5, 1], [6, 7, 2]]

In [6]:
# (i.)
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

# Matrix multiplication
product1 = np.dot(p1, q1)
print("Matrix Multiplication (p1 x q1):\n", product1)

# Covariance (flattening matrices)
combined1 = np.vstack((p1.flatten(), q1.flatten()))
cov_matrix1 = np.cov(combined1)
print("\nCovariance matrix between p1 and q1:\n", cov_matrix1)


# (ii.)
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

# Matrix multiplication
product2 = np.dot(p2, q2)
print("\nMatrix Multiplication (p2 x q2):\n", product2)

# Covariance (flattening matrices)
combined2 = np.vstack((p2.flatten(), q2.flatten()))
cov_matrix2 = np.cov(combined2)
print("\nCovariance matrix between p2 and q2:\n", cov_matrix2)


Matrix Multiplication (p1 x q1):
 [[16 19]
 [26 31]]

Covariance matrix between p1 and q1:
 [[0.66666667 1.        ]
 [1.         1.66666667]]

Matrix Multiplication (p2 x q2):
 [[16 19  5]
 [26 31  8]
 [46 55 14]]

Covariance matrix between p2 and q2:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [5]:
from itertools import product

# Define the arrays
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Inner Product
inner_product = np.inner(x, y)
print("Inner Product:\n", inner_product)

# Outer product
x_flat = x.flatten()
y_flat = y.flatten()
outer_product = np.outer(x_flat, y_flat)
print("\nOuter Product:\n", outer_product)

# Cartesian product
x_rows = x.tolist()
y_rows = y.tolist()
cartesian_product = list(product(x_rows, y_rows))

print("\nCartesian Product (row-wise pairs):")
for pair in cartesian_product:
    print(pair)


Inner Product:
 [[17 52]
 [13 62]]

Outer Product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian Product (row-wise pairs):
([2, 3, 4], [1, 5, 0])
([2, 3, 4], [5, 10, 3])
([3, 2, 9], [1, 5, 0])
([3, 2, 9], [5, 10, 3])


### Q2

(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
<br>i. Find element-wise absolute value
<br>ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row.
<br>iii. Mean, Median and Standard Deviation of flattened array, of each column, and each row

In [8]:
# Define the array
array = np.array([[1, -2, 3], [-4, 5, -6]])


# (i.)
abs_array = np.abs(array)
print("Element-wise Absolute Value:\n", abs_array)


# (ii.)
percentiles_flat = np.percentile(array, [25, 50, 75])
print("\nPercentiles of flattened array (25th, 50th, 75th):", percentiles_flat)

# Percentiles by column (axis=0)
percentiles_cols = np.percentile(array, [25, 50, 75], axis=0)
print("Percentiles for each column:\n", percentiles_cols)

# Percentiles by row (axis=1)
percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)
print("Percentiles for each row:\n", percentiles_rows)


# (iii.)
# Flattened
mean_flat = np.mean(array)
median_flat = np.median(array)
std_flat = np.std(array)
print("\nFlattened Array:")
print("Mean:", mean_flat)
print("Median:", median_flat)
print("Standard Deviation:", std_flat)

# By columns
mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)
print("\nColumn-wise:")
print("Mean:", mean_col)
print("Median:", median_col)
print("Standard Deviation:", std_col)

# By rows
mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)
print("\nRow-wise:")
print("Mean:", mean_row)
print("Median:", median_row)
print("Standard Deviation:", std_row)

Element-wise Absolute Value:
 [[1 2 3]
 [4 5 6]]

Percentiles of flattened array (25th, 50th, 75th): [-3.5 -0.5  2.5]
Percentiles for each column:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles for each row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]

Flattened Array:
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224

Column-wise:
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]

Row-wise:
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling and truncated value, rounded values

In [9]:
# Define the array
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

# Floor
floor_vals = np.floor(a)
print("Floor values: ", floor_vals)

# Ceiling
ceil_vals = np.ceil(a)
print("Ceiling values: ", ceil_vals)

# Truncated values (remove decimal part, toward zero)
trunc_vals = np.trunc(a)
print("Truncated values: ", trunc_vals)

# Rounded values (to nearest integer)
rounded_vals = np.round(a)
print("Rounded values: ", rounded_vals)

Floor values:  [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values:  [-1. -1. -0.  1.  2.  2.  3.]
Truncated values:  [-1. -1. -0.  0.  1.  1.  3.]
Rounded values:  [-2. -2. -0.  0.  2.  2.  3.]


### Q3

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
<br>i. Sorted array
<br>ii. Indices of sorted array
<br>iii. 4 smallest elements
<br>iv. 5 largest elements

In [10]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

# (i.)
sorted_array = np.sort(array)
print("Sorted array:", sorted_array)

# (ii.)
sorted_indices = np.argsort(array)
print("Indices of sorted array:", sorted_indices)

# (iii.)
smallest_4 = np.sort(array)[:4]
print("4 smallest elements:", smallest_4)

# (iv.)
largest_5 = np.sort(array)[-5:][::-1]  # or use np.partition for better performance
print("5 largest elements:", largest_5)


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [453  62  54  52  16]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
<br>i. Integer elements only
<br>ii. Float elements only

In [11]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# (i.)
integers_only = array[array == array.astype(int)]
print("Integer elements only:", integers_only)

# (ii.)
floats_only = array[array != array.astype(int)]
print("Float elements only:", floats_only)


Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


### Q4

(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)

In [13]:
import cv2
import numpy as np

def img_to_array(path):
    # Read image in color (OpenCV always loads as BGR, even if grayscale)
    img = cv2.imread(path, cv2.IMREAD_UNCHANGED)

    # Check if image is grayscale (2D array)
    if len(img.shape) == 2:
        # Grayscale image
        np.savetxt("image_array.txt", img, fmt='%d')
        print("Grayscale image detected.")
    elif len(img.shape) == 3 and img.shape[2] == 3:
        # RGB image (convert from BGR to RGB)
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        np.savetxt("image_array.txt", img_rgb.reshape(-1, 3), fmt='%d')
        print("RGB image detected.")
    else:
        print("Unsupported image format.")


image_path = "Bird.jpg"
img_to_array(image_path)

RGB image detected.


(b) Load the saved file into jupyter notebook?

In [15]:
# Load the text file
data = np.loadtxt("image_array.txt", dtype=int)
print("Loaded data:\n", data)

Loaded data:
 [[200 208 219]
 [199 207 218]
 [199 207 218]
 ...
 [222 226 235]
 [222 226 237]
 [223 227 238]]
